/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface Song {
  id: string
  bitrate?: number
  sampleRate?: number
  duration?: number
  path?: string
  size?: number
  title?: string
  album?: Album
  artists: Array<Artists>
  year?: string
  genre?: Array<string>
  lyrics?: string
  trackNo?: string
  song_coverPath_high?: string
  song_coverPath_low?: string
  type: string
  playlistId?: string
}
export interface Album {
  album_id: string
  album_name: string
  album_coverPath_high?: string
  album_coverPath_low?: string
}
export interface Artists {
  artist_id: string
  artist_name: string
}
export interface Playlist {
  id: string
  title: string
}
export interface SongWithLen {
  song: Song
  size: number
  current: number
}
export interface ErrorWithLen {
  error: string
  size: number
  current: number
}
export function scanFiles(dir: string, thumbnailDir: string, databaseDir: string, artistSplit: string, threads: number, force: boolean, callback_song: (err: null | Error, result: SongWithLen) => void, callback_playlist: (err: null | Error, result: Playlist) => void, callback_enc: (err: null | Error) => void): void
