/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface Song {
  bitrate?: number
  sampleRate?: number
  duration?: number
  path?: string
  size?: number
  title?: string
  album?: string
  artists?: string
  year?: string
  genre?: string
  lyrics?: string
  trackNo?: string
  highPath?: string
  lowPath?: string
  songType?: string
  playlistId?: number
}
export interface Playlist {
  id: number
  title: string
}
export function scanFiles(dir: string, thumbnailDir: string, databaseDir: string, callback: (err: null | Error, result: Song) => void, callback: (err: null | Error, result: Playlist) => void): void
